"""dev baseline

Revision ID: 7b60ccd424e5
Revises: 
Create Date: 2025-10-22 09:41:40.377402

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from app.models.types import CaseInsensitiveEnum as CIEnum
# Import enum classes used by CaseInsensitiveEnum columns
from app.models.calendar_account import CalendarProvider
from app.models.notification import NotificationType
from app.models.booking_status import BookingStatus
from app.models.message import SenderType, VisibleTo
from app.models.user import UserType


# revision identifiers, used by Alembic.
revision: str = '7b60ccd424e5'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('service_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_service_categories_id'), 'service_categories', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('phone_number', sa.String(), nullable=True),
    # Use the application enum to align DB type/values with models
    sa.Column('user_type', sa.Enum(UserType, name='usertype'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('mfa_secret', sa.String(), nullable=True),
    sa.Column('mfa_enabled', sa.Boolean(), nullable=True),
    sa.Column('mfa_recovery_tokens', sa.String(), nullable=True),
    sa.Column('profile_picture_url', sa.String(), nullable=True),
    sa.Column('refresh_token_hash', sa.String(), nullable=True),
    sa.Column('refresh_token_expires_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('admin_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', name='uq_admin_users_user_id')
    )
    op.create_index(op.f('ix_admin_users_email'), 'admin_users', ['email'], unique=True)
    op.create_index(op.f('ix_admin_users_id'), 'admin_users', ['id'], unique=False)
    op.create_index(op.f('ix_admin_users_user_id'), 'admin_users', ['user_id'], unique=False)
    # Ensure enum type exists on fresh DBs

    op.execute("""
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'calendarprovider') THEN
        CREATE TYPE calendarprovider AS ENUM ('google');
    END IF;
END
$$ LANGUAGE plpgsql;
""")

    op.create_table('calendar_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('provider', CIEnum(CalendarProvider, name='calendarprovider'), nullable=False),
    sa.Column('refresh_token', sa.String(), nullable=False),
    sa.Column('access_token', sa.String(), nullable=False),
    sa.Column('token_expiry', sa.DateTime(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_calendar_accounts_id'), 'calendar_accounts', ['id'], unique=False)
    op.create_index(op.f('ix_calendar_accounts_provider'), 'calendar_accounts', ['provider'], unique=False)
    op.create_index(op.f('ix_calendar_accounts_user_id'), 'calendar_accounts', ['user_id'], unique=False)
    op.create_table('email_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_email_tokens_id'), 'email_tokens', ['id'], unique=False)
    op.create_index(op.f('ix_email_tokens_token'), 'email_tokens', ['token'], unique=True)
    # Ensure enum type for notifications exists (used by notifications.type)
    op.execute("""
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'notificationtype') THEN
        CREATE TYPE notificationtype AS ENUM (
            'new_message',
            'new_booking_request',
            'booking_status_updated',
            'quote_accepted',
            'quote_expired',
            'quote_expiring',
            'new_booking',
            'deposit_due',
            'review_request'
        );
    END IF;
END
$$ LANGUAGE plpgsql;
""")

    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('type', CIEnum(NotificationType, name='notificationtype'), nullable=False),
    sa.Column('message', sa.String(), nullable=False),
    sa.Column('link', sa.String(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_id'), 'notifications', ['id'], unique=False)
    op.create_table('quote_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('artist_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('services', sa.JSON(), nullable=False),
    sa.Column('sound_fee', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('travel_fee', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('accommodation', sa.String(), nullable=True),
    sa.Column('discount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['artist_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quote_templates_id'), 'quote_templates', ['id'], unique=False)
    op.create_table('service_provider_profiles',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('business_name', sa.String(), nullable=True),
    sa.Column('custom_subtitle', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('hourly_rate', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('portfolio_urls', sa.JSON(), nullable=True),
    sa.Column('portfolio_image_urls', sa.JSON(), nullable=True),
    sa.Column('specialties', sa.JSON(), nullable=True),
    sa.Column('profile_picture_url', sa.String(), nullable=True),
    sa.Column('cover_photo_url', sa.String(), nullable=True),
    sa.Column('price_visible', sa.Boolean(), nullable=False),
    sa.Column('cancellation_policy', sa.Text(), nullable=True),
    sa.Column('onboarding_completed', sa.Boolean(), nullable=False),
    sa.Column('contact_email', sa.String(), nullable=True),
    sa.Column('contact_phone', sa.String(), nullable=True),
    sa.Column('contact_website', sa.String(), nullable=True),
    sa.Column('bank_name', sa.String(), nullable=True),
    sa.Column('bank_account_name', sa.String(), nullable=True),
    sa.Column('bank_account_number', sa.String(), nullable=True),
    sa.Column('bank_branch_code', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_service_provider_profiles_business_name'), 'service_provider_profiles', ['business_name'], unique=False)
    op.create_index(op.f('ix_service_provider_profiles_user_id'), 'service_provider_profiles', ['user_id'], unique=True)
    op.create_table('trusted_devices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'device_id', name='uq_trusted_device')
    )
    op.create_index(op.f('ix_trusted_devices_device_id'), 'trusted_devices', ['device_id'], unique=False)
    op.create_index(op.f('ix_trusted_devices_user_id'), 'trusted_devices', ['user_id'], unique=False)
    op.create_table('webauthn_credentials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('credential_id', sa.String(), nullable=False),
    sa.Column('public_key', sa.String(), nullable=True),
    sa.Column('sign_count', sa.Integer(), nullable=True),
    sa.Column('transports', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_webauthn_credentials_credential_id'), 'webauthn_credentials', ['credential_id'], unique=True)
    op.create_index(op.f('ix_webauthn_credentials_id'), 'webauthn_credentials', ['id'], unique=False)
    op.create_index(op.f('ix_webauthn_credentials_user_id'), 'webauthn_credentials', ['user_id'], unique=False)
    op.create_table('artist_profile_views',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('artist_id', sa.Integer(), nullable=False),
    sa.Column('viewer_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['artist_id'], ['service_provider_profiles.user_id'], ),
    sa.ForeignKeyConstraint(['viewer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_artist_profile_views_id'), 'artist_profile_views', ['id'], unique=False)
    op.create_table('services',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('artist_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('media_url', sa.String(), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('service_type', sa.Enum('Live Performance', 'Virtual Appearance', 'Personalized Video', 'Custom Song', 'Other', name='servicetype', native_enum=False), nullable=False),
    sa.Column('service_category_id', sa.Integer(), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('travel_rate', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('travel_members', sa.Integer(), nullable=True),
    sa.Column('car_rental_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('flight_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('sound_managed_markup_percent', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['artist_id'], ['service_provider_profiles.user_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['service_category_id'], ['service_categories.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_services_id'), 'services', ['id'], unique=False)
    op.create_index(op.f('ix_services_status'), 'services', ['status'], unique=False)
    op.create_index(op.f('ix_services_title'), 'services', ['title'], unique=False)
    # Ensure booking status enum exists before tables that use it
    op.execute("""
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'bookingstatus') THEN
        CREATE TYPE bookingstatus AS ENUM (
            'pending', 'confirmed', 'completed', 'cancelled', 'draft',
            'pending_quote', 'quote_provided', 'pending_artist_confirmation',
            'request_confirmed', 'request_completed', 'request_declined',
            'request_withdrawn', 'quote_rejected', 'pending_sound', 'failed_no_sound'
        );
    END IF;
END
$$ LANGUAGE plpgsql;
""")

    op.create_table('booking_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('artist_id', sa.Integer(), nullable=False),
    sa.Column('service_id', sa.Integer(), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('attachment_url', sa.String(), nullable=True),
    sa.Column('proposed_datetime_1', sa.DateTime(), nullable=True),
    sa.Column('proposed_datetime_2', sa.DateTime(), nullable=True),
    sa.Column('travel_mode', sa.String(), nullable=True),
    sa.Column('travel_cost', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('travel_breakdown', sa.JSON(), nullable=True),
    sa.Column('status', CIEnum(BookingStatus, name='bookingstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['artist_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['client_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_booking_requests_artist_id'), 'booking_requests', ['artist_id'], unique=False)
    op.create_index(op.f('ix_booking_requests_id'), 'booking_requests', ['id'], unique=False)
    op.create_index(op.f('ix_booking_requests_proposed_datetime_1'), 'booking_requests', ['proposed_datetime_1'], unique=False)
    op.create_index(op.f('ix_booking_requests_proposed_datetime_2'), 'booking_requests', ['proposed_datetime_2'], unique=False)
    op.create_index(op.f('ix_booking_requests_status'), 'booking_requests', ['status'], unique=False)
    op.create_table('riders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('service_id', sa.Integer(), nullable=False),
    sa.Column('spec', sa.JSON(), nullable=True),
    sa.Column('pdf_url', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_riders_id'), 'riders', ['id'], unique=False)
    op.create_index(op.f('ix_riders_service_id'), 'riders', ['service_id'], unique=False)
    op.create_table('supplier_pricebooks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('service_id', sa.Integer(), nullable=False),
    sa.Column('pricebook', sa.JSON(), nullable=False),
    sa.Column('km_rate', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('min_callout', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('reliability_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('base_location', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_supplier_pricebooks_id'), 'supplier_pricebooks', ['id'], unique=False)
    op.create_index(op.f('ix_supplier_pricebooks_service_id'), 'supplier_pricebooks', ['service_id'], unique=False)
    op.create_table('quotes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('booking_request_id', sa.Integer(), nullable=False),
    sa.Column('artist_id', sa.Integer(), nullable=False),
    sa.Column('quote_details', sa.Text(), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('valid_until', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Enum('pending_client_action', 'accepted_by_client', 'rejected_by_client', 'confirmed_by_artist', 'withdrawn_by_artist', 'expired', name='quotestatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['artist_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['booking_request_id'], ['booking_requests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quotes_id'), 'quotes', ['id'], unique=False)
    op.create_table('quotes_v2',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('booking_request_id', sa.Integer(), nullable=False),
    sa.Column('artist_id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('services', sa.JSON(), nullable=False),
    sa.Column('sound_fee', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('sound_firm', sa.String(), nullable=True),
    sa.Column('travel_fee', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('accommodation', sa.String(), nullable=True),
    sa.Column('subtotal', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('discount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('total', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('status', sa.Enum('pending', 'accepted', 'rejected', 'expired', name='quotestatusv2'), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['artist_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['booking_request_id'], ['booking_requests.id'], ),
    sa.ForeignKeyConstraint(['client_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quotes_v2_id'), 'quotes_v2', ['id'], unique=False)
    op.create_table('bookings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('artist_id', sa.Integer(), nullable=True),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('service_id', sa.Integer(), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=False),
    sa.Column('status', CIEnum(BookingStatus, name='bookingstatus'), nullable=True),
    sa.Column('total_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('event_city', sa.String(), nullable=True),
    sa.Column('artist_accept_deadline_at', sa.DateTime(), nullable=True),
    sa.Column('quote_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['artist_id'], ['service_provider_profiles.user_id'], ),
    sa.ForeignKeyConstraint(['client_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['quote_id'], ['quotes.id'], ),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bookings_artist_id'), 'bookings', ['artist_id'], unique=False)
    op.create_index(op.f('ix_bookings_id'), 'bookings', ['id'], unique=False)
    op.create_index(op.f('ix_bookings_start_time'), 'bookings', ['start_time'], unique=False)
    op.create_index(op.f('ix_bookings_status'), 'bookings', ['status'], unique=False)
    op.create_table('bookings_simple',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quote_id', sa.Integer(), nullable=False),
    sa.Column('artist_id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('confirmed', sa.Boolean(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('payment_status', sa.String(), nullable=False),
    sa.Column('payment_id', sa.String(), nullable=True),
    # deposit fields removed: full upfront payments only
    sa.Column('charged_total_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('artist_hold_id', sa.String(), nullable=True),
    sa.Column('artist_hold_status', sa.String(), nullable=True),
    sa.Column('artist_hold_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('sound_hold_id', sa.String(), nullable=True),
    sa.Column('sound_hold_status', sa.String(), nullable=True),
    sa.Column('sound_hold_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['artist_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['client_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['quote_id'], ['quotes_v2.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bookings_simple_id'), 'bookings_simple', ['id'], unique=False)
    # Ensure message-related enums exist before creating messages table
    op.execute("""
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'sendertype') THEN
        CREATE TYPE sendertype AS ENUM ('client', 'artist');
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'visibleto') THEN
        CREATE TYPE visibleto AS ENUM ('artist', 'client', 'both');
    END IF;
END
$$ LANGUAGE plpgsql;
""")

    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('booking_request_id', sa.Integer(), nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=False),
    sa.Column('sender_type', CIEnum(SenderType, name='sendertype'), nullable=False),
    sa.Column('message_type', sa.Enum('USER', 'QUOTE', 'SYSTEM', 'TEXT', name='messagetype'), nullable=False),
    sa.Column('visible_to', CIEnum(VisibleTo, name='visibleto'), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('quote_id', sa.Integer(), nullable=True),
    sa.Column('attachment_url', sa.String(), nullable=True),
    sa.Column('attachment_meta', sa.JSON(), nullable=True),
    sa.Column('action', sa.Enum('REVIEW_QUOTE', 'VIEW_BOOKING_DETAILS', name='messageaction'), nullable=True),
    sa.Column('system_key', sa.String(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('reply_to_message_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['booking_request_id'], ['booking_requests.id'], ),
    sa.ForeignKeyConstraint(['quote_id'], ['quotes_v2.id'], ),
    sa.ForeignKeyConstraint(['reply_to_message_id'], ['messages.id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('booking_request_id', 'system_key', name='uq_messages_request_system_key')
    )
    op.create_index(op.f('ix_messages_id'), 'messages', ['id'], unique=False)
    op.create_index('ix_messages_request_id_id', 'messages', ['booking_request_id', 'id'], unique=False)
    op.create_index('ix_messages_request_time', 'messages', ['booking_request_id', 'timestamp'], unique=False)
    op.create_index('ix_messages_request_type_time', 'messages', ['booking_request_id', 'message_type', 'timestamp'], unique=False)
    op.create_index(op.f('ix_messages_system_key'), 'messages', ['system_key'], unique=False)
    op.create_table('event_prep_idempotency',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('booking_id', sa.Integer(), nullable=True),
    sa.Column('key_hash', sa.String(), nullable=False),
    sa.Column('request_hash', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('booking_id', 'key_hash', name='uq_event_prep_idem_booking_key')
    )
    op.create_index(op.f('ix_event_prep_idempotency_booking_id'), 'event_prep_idempotency', ['booking_id'], unique=False)
    op.create_index(op.f('ix_event_prep_idempotency_id'), 'event_prep_idempotency', ['id'], unique=False)
    op.create_table('event_preps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('booking_id', sa.Integer(), nullable=False),
    sa.Column('day_of_contact_name', sa.String(), nullable=True),
    sa.Column('day_of_contact_phone', sa.String(), nullable=True),
    sa.Column('venue_address', sa.String(), nullable=True),
    sa.Column('venue_place_id', sa.String(), nullable=True),
    sa.Column('venue_lat', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('venue_lng', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('loadin_start', sa.Time(), nullable=True),
    sa.Column('loadin_end', sa.Time(), nullable=True),
    sa.Column('soundcheck_time', sa.Time(), nullable=True),
    sa.Column('guests_arrival_time', sa.Time(), nullable=True),
    sa.Column('performance_start_time', sa.Time(), nullable=True),
    sa.Column('performance_end_time', sa.Time(), nullable=True),
    sa.Column('tech_owner', sa.String(), nullable=False),
    sa.Column('stage_power_confirmed', sa.Boolean(), nullable=False),
    sa.Column('accommodation_required', sa.Boolean(), nullable=False),
    sa.Column('accommodation_address', sa.String(), nullable=True),
    sa.Column('accommodation_contact', sa.String(), nullable=True),
    sa.Column('accommodation_notes', sa.String(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('schedule_notes', sa.String(), nullable=True),
    sa.Column('parking_access_notes', sa.String(), nullable=True),
    sa.Column('event_type', sa.String(), nullable=True),
    sa.Column('guests_count', sa.Integer(), nullable=True),
    sa.Column('progress_cached', sa.Integer(), nullable=False),
    sa.Column('updated_by_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('booking_id', name='uq_event_preps_booking_id')
    )
    op.create_index(op.f('ix_event_preps_booking_id'), 'event_preps', ['booking_id'], unique=True)
    op.create_index(op.f('ix_event_preps_id'), 'event_preps', ['id'], unique=False)
    op.create_table('invoices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quote_id', sa.Integer(), nullable=False),
    sa.Column('booking_id', sa.Integer(), nullable=False),
    sa.Column('artist_id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('issue_date', sa.Date(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('amount_due', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('status', sa.Enum('unpaid', 'partial', 'paid', 'overdue', name='invoicestatus'), nullable=False),
    sa.Column('payment_method', sa.String(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('pdf_url', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['artist_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings_simple.id'], ),
    sa.ForeignKeyConstraint(['client_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['quote_id'], ['quotes_v2.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invoices_id'), 'invoices', ['id'], unique=False)
    op.create_table('message_reactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('emoji', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('message_id', 'user_id', 'emoji', name='uq_msg_reaction')
    )
    op.create_index(op.f('ix_message_reactions_id'), 'message_reactions', ['id'], unique=False)
    op.create_index('ix_msg_reaction_message', 'message_reactions', ['message_id'], unique=False)
    op.create_table('reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('booking_id', sa.Integer(), nullable=False),
    sa.Column('service_id', sa.Integer(), nullable=False),
    sa.Column('artist_id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['artist_id'], ['service_provider_profiles.user_id'], ),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reviews_id'), 'reviews', ['id'], unique=False)
    op.create_table('sound_outreach_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('booking_id', sa.Integer(), nullable=False),
    sa.Column('supplier_service_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('SENT', 'ACCEPTED', 'DECLINED', 'EXPIRED', name='outreachstatus'), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('responded_at', sa.DateTime(), nullable=True),
    sa.Column('lock_token', sa.String(), nullable=False),
    sa.Column('accepted_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('supplier_booking_request_id', sa.Integer(), nullable=True),
    sa.Column('supplier_quote_id', sa.Integer(), nullable=True),
    sa.Column('supplier_public_name', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['supplier_booking_request_id'], ['booking_requests.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['supplier_quote_id'], ['quotes.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['supplier_service_id'], ['services.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sound_outreach_requests_booking_id'), 'sound_outreach_requests', ['booking_id'], unique=False)
    op.create_index(op.f('ix_sound_outreach_requests_id'), 'sound_outreach_requests', ['id'], unique=False)
    op.create_index(op.f('ix_sound_outreach_requests_lock_token'), 'sound_outreach_requests', ['lock_token'], unique=False)
    op.create_index(op.f('ix_sound_outreach_requests_status'), 'sound_outreach_requests', ['status'], unique=False)
    op.create_table('event_prep_attachments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_prep_id', sa.Integer(), nullable=False),
    sa.Column('file_url', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['event_prep_id'], ['event_preps.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_event_prep_attachments_event_prep_id'), 'event_prep_attachments', ['event_prep_id'], unique=False)
    op.create_index(op.f('ix_event_prep_attachments_id'), 'event_prep_attachments', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_event_prep_attachments_id'), table_name='event_prep_attachments')
    op.drop_index(op.f('ix_event_prep_attachments_event_prep_id'), table_name='event_prep_attachments')
    op.drop_table('event_prep_attachments')
    op.drop_index(op.f('ix_sound_outreach_requests_status'), table_name='sound_outreach_requests')
    op.drop_index(op.f('ix_sound_outreach_requests_lock_token'), table_name='sound_outreach_requests')
    op.drop_index(op.f('ix_sound_outreach_requests_id'), table_name='sound_outreach_requests')
    op.drop_index(op.f('ix_sound_outreach_requests_booking_id'), table_name='sound_outreach_requests')
    op.drop_table('sound_outreach_requests')
    op.drop_index(op.f('ix_reviews_id'), table_name='reviews')
    op.drop_table('reviews')
    op.drop_index('ix_msg_reaction_message', table_name='message_reactions')
    op.drop_index(op.f('ix_message_reactions_id'), table_name='message_reactions')
    op.drop_table('message_reactions')
    op.drop_index(op.f('ix_invoices_id'), table_name='invoices')
    op.drop_table('invoices')
    op.drop_index(op.f('ix_event_preps_id'), table_name='event_preps')
    op.drop_index(op.f('ix_event_preps_booking_id'), table_name='event_preps')
    op.drop_table('event_preps')
    op.drop_index(op.f('ix_event_prep_idempotency_id'), table_name='event_prep_idempotency')
    op.drop_index(op.f('ix_event_prep_idempotency_booking_id'), table_name='event_prep_idempotency')
    op.drop_table('event_prep_idempotency')
    op.drop_index(op.f('ix_messages_system_key'), table_name='messages')
    op.drop_index('ix_messages_request_type_time', table_name='messages')
    op.drop_index('ix_messages_request_time', table_name='messages')
    op.drop_index('ix_messages_request_id_id', table_name='messages')
    op.drop_index(op.f('ix_messages_id'), table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_bookings_simple_id'), table_name='bookings_simple')
    op.drop_table('bookings_simple')
    op.drop_index(op.f('ix_bookings_status'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_start_time'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_id'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_artist_id'), table_name='bookings')
    op.drop_table('bookings')
    op.drop_index(op.f('ix_quotes_v2_id'), table_name='quotes_v2')
    op.drop_table('quotes_v2')
    op.drop_index(op.f('ix_quotes_id'), table_name='quotes')
    op.drop_table('quotes')
    op.drop_index(op.f('ix_supplier_pricebooks_service_id'), table_name='supplier_pricebooks')
    op.drop_index(op.f('ix_supplier_pricebooks_id'), table_name='supplier_pricebooks')
    op.drop_table('supplier_pricebooks')
    op.drop_index(op.f('ix_riders_service_id'), table_name='riders')
    op.drop_index(op.f('ix_riders_id'), table_name='riders')
    op.drop_table('riders')
    op.drop_index(op.f('ix_booking_requests_status'), table_name='booking_requests')
    op.drop_index(op.f('ix_booking_requests_proposed_datetime_2'), table_name='booking_requests')
    op.drop_index(op.f('ix_booking_requests_proposed_datetime_1'), table_name='booking_requests')
    op.drop_index(op.f('ix_booking_requests_id'), table_name='booking_requests')
    op.drop_index(op.f('ix_booking_requests_artist_id'), table_name='booking_requests')
    op.drop_table('booking_requests')
    op.drop_index(op.f('ix_services_title'), table_name='services')
    op.drop_index(op.f('ix_services_status'), table_name='services')
    op.drop_index(op.f('ix_services_id'), table_name='services')
    op.drop_table('services')
    op.drop_index(op.f('ix_artist_profile_views_id'), table_name='artist_profile_views')
    op.drop_table('artist_profile_views')
    op.drop_index(op.f('ix_webauthn_credentials_user_id'), table_name='webauthn_credentials')
    op.drop_index(op.f('ix_webauthn_credentials_id'), table_name='webauthn_credentials')
    op.drop_index(op.f('ix_webauthn_credentials_credential_id'), table_name='webauthn_credentials')
    op.drop_table('webauthn_credentials')
    op.drop_index(op.f('ix_trusted_devices_user_id'), table_name='trusted_devices')
    op.drop_index(op.f('ix_trusted_devices_device_id'), table_name='trusted_devices')
    op.drop_table('trusted_devices')
    op.drop_index(op.f('ix_service_provider_profiles_user_id'), table_name='service_provider_profiles')
    op.drop_index(op.f('ix_service_provider_profiles_business_name'), table_name='service_provider_profiles')
    op.drop_table('service_provider_profiles')
    op.drop_index(op.f('ix_quote_templates_id'), table_name='quote_templates')
    op.drop_table('quote_templates')
    op.drop_index(op.f('ix_notifications_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_email_tokens_token'), table_name='email_tokens')
    op.drop_index(op.f('ix_email_tokens_id'), table_name='email_tokens')
    op.drop_table('email_tokens')
    op.drop_index(op.f('ix_calendar_accounts_user_id'), table_name='calendar_accounts')
    op.drop_index(op.f('ix_calendar_accounts_provider'), table_name='calendar_accounts')
    op.drop_index(op.f('ix_calendar_accounts_id'), table_name='calendar_accounts')
    op.drop_table('calendar_accounts')
    op.drop_index(op.f('ix_admin_users_user_id'), table_name='admin_users')
    op.drop_index(op.f('ix_admin_users_id'), table_name='admin_users')
    op.drop_index(op.f('ix_admin_users_email'), table_name='admin_users')
    op.drop_table('admin_users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_service_categories_id'), table_name='service_categories')
    op.drop_table('service_categories')
    # ### end Alembic commands ###
