"""add sessions table

Revision ID: ed57deb9c434
Revises: b1b2c3d4e5f6
Create Date: 2025-11-10 13:35:22.133244

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ed57deb9c434'
down_revision: Union[str, None] = 'b1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.create_table(
        "sessions",
        sa.Column("id", sa.Integer(), primary_key=True),
        sa.Column(
            "user_id",
            sa.Integer(),
            sa.ForeignKey("users.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column("refresh_token_hash", sa.String(length=128), nullable=True),
        sa.Column("refresh_token_expires_at", sa.DateTime(), nullable=True),
        sa.Column("refresh_jti", sa.String(length=64), nullable=True),
        sa.Column("prev_refresh_token_hash", sa.String(length=128), nullable=True),
        sa.Column("prev_rotated_at", sa.DateTime(), nullable=True),
        sa.Column("revoked_at", sa.DateTime(), nullable=True),
        sa.Column("last_used_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
    )
    op.create_index("ix_sessions_user_id", "sessions", ["user_id"])
    op.create_index(
        "ix_sessions_refresh_jti", "sessions", ["refresh_jti"], unique=True
    )
    op.create_index(
        "ix_sessions_refresh_hash", "sessions", ["refresh_token_hash"]
    )
    op.create_index("ix_sessions_revoked_at", "sessions", ["revoked_at"])


def downgrade() -> None:
    op.drop_index("ix_sessions_revoked_at", table_name="sessions")
    op.drop_index("ix_sessions_refresh_hash", table_name="sessions")
    op.drop_index("ix_sessions_refresh_jti", table_name="sessions")
    op.drop_index("ix_sessions_user_id", table_name="sessions")
    op.drop_table("sessions")


# ---------------------------------------------------------------------------
# Manual schema notes (ed57deb9c434 baseline)
#
# 2025-11-27:
#   On production appdb at revision ed57deb9c434 (this file), we manually added
#   booking_requests.parent_booking_request_id with:
#     ALTER TABLE booking_requests
#       ADD COLUMN parent_booking_request_id integer;
#     CREATE INDEX ix_booking_requests_parent_booking_request_id
#       ON booking_requests (parent_booking_request_id);
#     ALTER TABLE booking_requests
#       ADD CONSTRAINT fk_booking_requests_parent_booking_request_id
#       FOREIGN KEY (parent_booking_request_id)
#       REFERENCES booking_requests(id)
#       ON DELETE SET NULL;
#   This change is not represented as an Alembic upgrade step; it is tracked
#   here and in AGENTS.md so future manual DB changes at this baseline can
#   follow the same pattern.
#
# 2025-12-12:
#   On production appdb at revision ed57deb9c434 (this file), prepare PV v2
#   schema with:
#     ALTER TABLE bookings_simple
#       ADD COLUMN booking_request_id integer NULL
#       REFERENCES booking_requests(id) ON DELETE SET NULL;
#     ALTER TABLE bookings_simple
#       ADD COLUMN booking_type varchar NOT NULL DEFAULT 'standard';
#     CREATE INDEX ix_bookings_simple_booking_request_id
#       ON bookings_simple (booking_request_id);
#     CREATE INDEX ix_bookings_simple_booking_type
#       ON bookings_simple (booking_type);
#     UPDATE bookings_simple bs
#     SET booking_request_id = q.booking_request_id,
#         booking_type = COALESCE(bs.booking_type, 'standard')
#     FROM quotes_v2 q
#     WHERE bs.quote_id = q.id
#       AND bs.booking_request_id IS NULL;
#     UPDATE bookings_simple
#     SET booking_type='standard'
#     WHERE booking_type IS NULL OR booking_type='';
#     ALTER TABLE quotes_v2
#       ADD COLUMN is_internal boolean NOT NULL DEFAULT false;
#     CREATE INDEX ix_quotes_v2_is_internal
#       ON quotes_v2 (is_internal);
#     ALTER TABLE disputes
#       ALTER COLUMN booking_id DROP NOT NULL;
#     ALTER TABLE disputes
#       ADD COLUMN booking_simple_id integer NULL
#       REFERENCES bookings_simple(id) ON DELETE SET NULL;
#     CREATE INDEX ix_disputes_booking_simple_id
#       ON disputes (booking_simple_id);
#     ALTER TABLE disputes
#       ADD CONSTRAINT ck_disputes_exactly_one_booking_ref
#       CHECK (num_nonnulls(booking_id, booking_simple_id) = 1);
#     -- Run outside a txn if using CONCURRENTLY
#     CREATE INDEX CONCURRENTLY ix_booking_requests_service_extras_pv
#       ON booking_requests
#       USING GIN ((service_extras::jsonb))
#       WHERE service_extras::jsonb ? 'pv';
#     -- Optional (Phase C): PV v2 idempotency table for create-order
#     CREATE TABLE IF NOT EXISTS video_order_idempotency (
#       id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
#       user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
#       key_hash VARCHAR NOT NULL,
#       request_hash VARCHAR NULL,
#       booking_request_id INTEGER NOT NULL REFERENCES booking_requests(id) ON DELETE CASCADE,
#       created_at TIMESTAMP NULL,
#       updated_at TIMESTAMP NULL,
#       CONSTRAINT uq_video_order_idem_user_key UNIQUE (user_id, key_hash)
#     );
#     CREATE INDEX ix_video_order_idempotency_user_id
#       ON video_order_idempotency (user_id);
#     CREATE INDEX ix_video_order_idempotency_booking_request_id
#       ON video_order_idempotency (booking_request_id);
#   This change is manual-only (no Alembic upgrade); also recorded in AGENTS.md.
#
# 2025-12-15:
#   On appdb at revision ed57deb9c434 (this file), add a marketing opt-in flag
#   to support client account preferences:
#     ALTER TABLE users
#       ADD COLUMN IF NOT EXISTS marketing_opt_in boolean NOT NULL DEFAULT FALSE;
#   This change is manual-only (no Alembic upgrade step). When recreating
#   appdb at this revision, re-apply the same DDL before deploying code that
#   reads or writes users.marketing_opt_in.
#
# 2025-12-19:
#   On appdb at revision ed57deb9c434 (this file), extend users with optional
#   organization and job title fields for client profiles:
#     ALTER TABLE users
#       ADD COLUMN IF NOT EXISTS organization varchar NULL;
#     ALTER TABLE users
#       ADD COLUMN IF NOT EXISTS job_title varchar NULL;
#   This change is manual-only (no Alembic upgrade step). When recreating
#   appdb at this revision, re-apply the same DDL before deploying code that
#   reads or writes users.organization / users.job_title.
#
# 2026-01-02:
#   On production appdb at revision ed57deb9c434 (this file), add an index to
#   speed provider rating aggregates on the reviews table:
#     CREATE INDEX ix_reviews_artist_id ON reviews (artist_id);
#   This is manual-only (no Alembic upgrade); also recorded in AGENTS.md.
#
# 2026-01-10:
#   On production appdb at revision ed57deb9c434 (this file), extend calendar
#   accounts with basic health metadata so Calendar Sync never "disconnects"
#   implicitly when Google rejects tokens:
#     ALTER TABLE calendar_accounts
#       ADD COLUMN status varchar NULL,
#       ADD COLUMN last_error text NULL,
#       ADD COLUMN last_error_at timestamp NULL,
#       ADD COLUMN last_success_sync_at timestamp NULL;
#   This change is manual-only (no Alembic upgrade step). When recreating
#   appdb at this revision, re-apply the same DDL before deploying code that
#   reads or writes these columns.
#
# 2026-01-10:
#   On production appdb at revision ed57deb9c434 (this file), add optional
#   geocoded coordinates for the provider base location so that artist lists
#   can be ordered by proximity ("Closest first") without changing the
#   existing human-readable `location` field:
#     ALTER TABLE service_provider_profiles
#       ADD COLUMN location_lat numeric(9, 6) NULL;
#     ALTER TABLE service_provider_profiles
#       ADD COLUMN location_lng numeric(9, 6) NULL;
#     CREATE INDEX ix_service_provider_profiles_location_lat
#       ON service_provider_profiles (location_lat);
#     CREATE INDEX ix_service_provider_profiles_location_lng
#       ON service_provider_profiles (location_lng);
#   This change is manual-only (no Alembic upgrade step). When recreating
#   appdb at this revision, re-apply the same DDL before deploying any code
#   that reads or writes these columns.
#
# 2026-01-15:
#   On production appdb at revision ed57deb9c434 (this file), add a generic
#   JSON extras payload for service-specific booking data (e.g. Personalized
#   Video orders) on booking_requests:
#     ALTER TABLE booking_requests
#       ADD COLUMN service_extras JSON;
#   This change is manual-only (no Alembic upgrade step). When recreating
#   appdb at this revision, re-apply the same DDL before deploying code that
#   reads or writes booking_requests.service_extras.
