name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'
      - name: Compute cache keys
        id: vars
        run: |
          echo "PY_VER=$(python -V | awk '{print $2}')" >> "$GITHUB_ENV"
          echo "NODE_VER=$(node -v | sed 's/^v//')" >> "$GITHUB_ENV"
          echo "BACKEND_HASH=$(sha256sum backend/requirements.txt requirements-dev.txt | sha256sum | awk '{print $1}')" >> "$GITHUB_ENV"
          echo "FRONTEND_HASH=$(sha256sum frontend/package-lock.json | awk '{print $1}')" >> "$GITHUB_ENV"
      - name: Cache backend archive
        uses: actions/cache@v4
        with:
          path: backend/venv.tar.zst
          key: venv-${{ env.PY_VER }}-${{ env.BACKEND_HASH }}-${{ runner.os }}
      - name: Cache frontend archive
        uses: actions/cache@v4
        with:
          path: frontend/node_modules.tar.zst
          key: node-${{ env.NODE_VER }}-${{ env.FRONTEND_HASH }}-${{ runner.os }}
      - name: Setup dependencies
        run: ./setup.sh
      - name: Run tests
        run: |
          if [[ $GITHUB_REF != 'refs/heads/main' ]]; then
            FAST=1 ./scripts/test-all.sh
          else
            ./scripts/test-all.sh
            FORCE=1 ./scripts/build-caches.sh
          fi
      - name: Mobile performance budgets
        run: cd frontend && npx playwright test e2e/mobile-performance.spec.ts --project=mobile-ios --project=mobile-android --reporter=line
      - name: Upload caches
        if: github.ref == 'refs/heads/main'
        uses: actions/upload-artifact@v4
        with:
          name: dependency-caches
          path: |
            backend/venv.tar.zst
            frontend/node_modules.tar.zst

